import {
  faEye,
  faHandPeace,
  faBolt,
  faBomb,
  faCode,
  faClover,
  faCookie,
  faDatabase,
  faCube,
  faDiceSix,
  faEgg,
  faFutbol,
  faGamepad,
  faGem,
  faHatCowboy,
  faInfinity,
  faJedi,
  faPaperPlane,
} from "@fortawesome/free-solid-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-common-types";

export const iconData = [
  "faEye",
  "faHandPeace",
  "faBolt",
  "faBomb",
  "faCode",
  "faClover",
  "faCookie",
  "faDatabase",
  "faCube",
  "faDiceSix",
  "faEgg",
  "faFutbol",
  "faGamepad",
  "faGem",
  "faHatCowboy",
  "faInfinity",
  "faJedi",
  "faPaperPlane",
];

export const iconMappings = [{ faEye: faEye }];

export const iconMapping: { [key: string]: IconDefinition } = {
  faEye: faEye,
  faHandPeace: faHandPeace,
  faBolt: faBolt,
  faBomb: faBomb,
  faCode: faCode,
  faClover: faClover,
  faCookie: faCookie,
  faDatabase: faDatabase,
  faCube: faCube,
  faDiceSix: faDiceSix,
  faEgg: faEgg,
  faFutbol: faFutbol,
  faGamepad: faGamepad,
  faGem: faGem,
  faHatCowboy: faHatCowboy,
  faInfinity: faInfinity,
  faJedi: faJedi,
  faPaperPlane: faPaperPlane,
};
